variables:
   REGISTRY_IMAGE: registry.gitlab.com/bouchtateam/petclinic:$CI_COMMIT_REF_NAME

stages:
   - build
   - run


build_docker_petclinic:
     stage: build
     script:
         
       - sudo docker login -u bouchtateam -p $pwdgitlab  registry.gitlab.com
       - sudo docker build -t $REGISTRY_IMAGE .
       - sudo docker push  $REGISTRY_IMAGE
     tags:
        - build
run_docker_petclinic:
    stage: run
    script:
         - sudo docker login -u bouchtateam -p $pwdgitlab  registry.gitlab.com
         - sudo docker pull  $REGISTRY_IMAGE
         - sudo docker rm -f petclinic || true
         - sudo docker run -d -p 9090:8080 -name petclinic --link mysql:mysql $REGISTRY_IMAGE  
    tags:
     - run
