variables:
   REGISTRY_IMAGE: registry.gitlab.com/bouchtateam/petclinic:$CI_COMMIT_REF_NAME

stages:
   - build
   - run


build_docker_petclinic:
     stage: build
     script:
         
       - docker login -u bouchtateam -p $pwdgitlab  registry.gitlab.com
       - docker build -t $REGISTRY_IMAGE .
       - docker push  $REGISTRY_IMAGE
     tags:
        - build
run_docker_petclinic:
    stage: run
    script:
         - docker login -u bouchtateam -p $pwdgitlab  registry.gitlab.com
         - docker pull  $REGISTRY_IMAGE
         - docker rm -f petclinic || true
         - docker run -d -p 9090:8080 -name petclinic --link mysql:mysql $REGISTRY_IMAGE  
    tags:
     - run
