# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  

stages:
- stage: Compile
  displayName: 'Compile Stage'

  displayName: 'Build and Compile'
  steps:
  - script: powershell mvn compile
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Compile
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: myagent

    steps:
     
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      inputs:
            containerRegistry: 'docker'
            repository: 'dohaeli13 / projetpfa'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'

